services:
  avr-core:
    image: agentvoiceresponse/avr-core
    platform: linux/x86_64
    container_name: avr-core
    restart: always
    environment:
      - PORT=5001 
      - ASR_URL=http://avr-asr-vosk:6010/speech-to-text-stream
      - LLM_URL=http://avr-llm-openai:6002/prompt-stream
      - TTS_URL=http://avr-tts-kokoro:6012/text-to-speech-stream
      - INTERRUPT_LISTENING=true
      - SYSTEM_MESSAGE="Hello, how can I help you today?"
    ports:
      - 5001:5001
    networks:
      - avr

  avr-asr-vosk:
    image: agentvoiceresponse/avr-asr-vosk
    platform: linux/x86_64
    container_name: avr-asr-vosk
    restart: always
    environment:
      - PORT=6010
      - MODEL_PATH=model
    volumes:
      - ./model:/usr/src/app/model
    networks:
      - avr

  avr-tts-kokoro:
    image: agentvoiceresponse/avr-tts-kokoro
    platform: linux/x86_64
    container_name: avr-tts-kokoro
    restart: always
    environment:
      - PORT=6012
      - KOKORO_BASE_URL=http://avr-kokoro:8880
      - KOKORO_VOICE=${KOKORO_VOICE:-af_alloy}
      - KOKORO_SPEED=${KOKORO_SPEED:-1.3}
    networks:
      - avr
  
  avr-kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-cpu
    container_name: avr-kokoro
    restart: always
    ports:
      - 8880:8880
    networks:
      - avr

  avr-llm-openai:
    image: agentvoiceresponse/avr-llm-openai
    platform: linux/x86_64
    container_name: avr-llm-openai
    restart: always
    environment:
      - PORT=6002
      - OPENAI_BASEURL=http://avr-ollama:11434/v1
      - OPENAI_API_KEY=sk-2cf236d3169945adac3df0324722c37c
      - OPENAI_MODEL=tinyllama
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-100}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.0}
      - AMI_URL=${AMI_URL:-http://avr-ami:6006}
      - SYSTEM_PROMPT="You are a helpful assistant."
    networks:
      - avr 

  avr-ollama:
    image: ollama/ollama
    container_name: avr-ollama
    restart: always
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama
    networks:
      - avr

  avr-ollama-web:
    image: ghcr.io/open-webui/open-webui
    container_name: avr-ollama-web
    restart: always
    ports:
      - 3001:8080
    volumes:
      - ./ollama-web:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://avr-ollama:11434
    networks:
      - avr
  
  avr-asterisk:
    image: agentvoiceresponse/avr-asterisk
    platform: linux/x86_64
    container_name: avr-asterisk
    restart: always
    ports:
      - 5038:5038
      - 5060:5060
      - 8088:8088
      - 8089:8089
      - 10000-10050:10000-10050/udp
    volumes:
      - ./asterisk/conf/manager.conf:/etc/asterisk/my_manager.conf
      - ./asterisk/conf/pjsip.conf:/etc/asterisk/my_pjsip.conf
      - ./asterisk/conf/extensions.conf:/etc/asterisk/my_extensions.conf
      - ./asterisk/conf/queues.conf:/etc/asterisk/my_queues.conf
      - ./asterisk/conf/ari.conf:/etc/asterisk/my_ari.conf
    networks:
      - avr

  avr-ami:
    image: agentvoiceresponse/avr-ami
    platform: linux/x86_64
    container_name: avr-ami
    restart: always
    environment:
      - PORT=6006
      - AMI_HOST=${AMI_HOST:-avr-asterisk}
      - AMI_PORT=${AMI_PORT:-5038}
      - AMI_USERNAME=${AMI_USERNAME:-avr}
      - AMI_PASSWORD=${AMI_PASSWORD:-avr}
    ports:
      - 6006:6006
    networks:
      - avr

networks:
  avr:
    name: avr
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          